import os

from snakebids import bids


configfile: "config/snakebids.yml"


# use expandvars so we can use e.g. '$SLURM_TMPDIR'
root = os.path.expandvars(config["root"])


# Input images are discovered at planning time (see rules/common.smk and
# neuropro/discovery.py): T1w runs use mixed naming that pybids/snakebids
# cannot express as one path template, and NM-GRE images come in several
# conventions, none of which is reliably BIDS.
include: "rules/common.smk"


wildcard_constraints:
    subject="[a-zA-Z0-9]+",
    session="[a-zA-Z0-9]+",
    tissue="[a-zA-Z]+",


def for_each_entry(**entities):
    """Expand a bids() path over every subject (and session) to be processed."""
    return expand(bids(root=root, **entities, **subj_wildcards), zip, **target_entities)


rule all_participant:
    default_target: True
    input:
        # final deliverable: smoothed, normalized NM average
        for_each_entry(
            datatype="anat",
            space=template_name,
            desc="smoothed",
            suffix="NM.nii.gz",
        ),
        # NM average coregistered to the subject's T1w
        for_each_entry(datatype="anat", space="T1w", desc="avg", suffix="NM.nii.gz"),
        # tissue segmentations
        [
            for_each_entry(datatype="anat", label=tissue, suffix="probseg.nii.gz")
            for tissue in ["CSF", "GM", "WM"]
        ],
        for_each_entry(datatype="anat", suffix="dseg.nii.gz"),
        # QC snapshots
        [
            for_each_entry(datatype="qc", desc=qc, suffix="qc.png")
            for qc in ["coreg", "seg", "norm"]
        ],


rule all_group:
    input:
        os.path.join(root, "group", "qc_summary.tsv"),
        os.path.join(root, "group", "qc_index.html"),


include: "rules/t1w.smk"
include: "rules/nm.smk"
include: "rules/normalize.smk"
include: "rules/qc.smk"
